<?php

namespace GildedRose\Tests;

use GildedRose\Item;
use GildedRose\Program;

class GildedRoseTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function qualityDegradesTwiceFastTest()
    {
        $items = array(
            new Item(array( 'name' => "+5 Dexterity Vest",'sellIn' => 0,'quality' => 20)),
            new Item(array( 'name' => "Aged Brie",'sellIn' => 1,'quality' => 30)),
        );

        $app = new Program();

        $items = $app->updateQuality($items);


    }
}

